### ISSUE TITLE
Fix no space between sentences.

### ISSUE THREAD

**Issue by jcandan** [jcandan/math_quiz#1]
There is no space between the sentences in the description. Simpy add a space to the end of the first sentence.

_Anyone is welcome to submit a PR for this issue. I will leave this issue open for the duration of Hacktoberfest 2017. Merge not required for Hacktoberfest. Don't feel bad if yours is not merged, my daughter will get that honor. ;)_

**Comment by nidble** [comment]
Can I take this issue?
