### ISSUE TITLE
remove negative equations

### ISSUE THREAD

**Issue by sophiesevim** [jcandan/math_quiz#16]
My daddy was trying to write a program, but he messed up and did the subtraction equations wrong. He put the equations to where we would go in the negatives.
we

**Comment by iulyaav** [comment]
May I have a look at this?

**Comment by jcandan** [comment]
sure! I would actually like to make this optional. so, `-n` would be a true flag allowing negative resulting equations, otherwise flip the terms to ensure a positive result.

**Comment by iulyaav** [comment]
Alright ^.^

**Comment by iulyaav** [comment]
Added with #35
Also, thanks. This was my first pull request for an open source project. So, I guess, no more first-timer fears for me anymore :)
