### ISSUE TITLE
Fix spelling error in help example description

### ISSUE THREAD

**Issue by jcandan** [jcandan/math_quiz#36]
The final example in the epilog has "Multiply" misspelled. Please fix this spelling error.

_Anyone is welcome to submit a PR for this issue. I will leave this issue open for the duration of Hacktoberfest 2017. Merge not required for Hacktoberfest. Don't feel bad if yours is not merged, my daughter will get that honor. ;)_

**Comment by umarbrowser** [comment]
hello can i do that i am assign

**Comment by GautamMandsorwale** [comment]
Hey @jcandan ,

Request you to check and approve this PR.
https://github.com/jcandan/math_quiz/pull/63

Thanks Again!
