### ISSUE TITLE
Add header to README

### ISSUE THREAD

**Issue by jcandan** [jcandan/math_quiz#5]
Please add the name of this project as a header to the README as markdown.

It's okay to google how to write a header in markdown.

_Anyone is welcome to submit a PR for this issue. I will leave this issue open for the duration of Hacktoberfest 2017. Merge not required for Hacktoberfest. Don't feel bad if yours is not merged, my daughter will get that honor. ;)_

**Comment by ayush-anand-13** [comment]
Can I take this up?
